---
- name: Test to get names from libvirt
  hosts: all
  become: true
  tasks:
    - name: List all vms in libvirt instance
      community.libvirt.virt:
        command: list_vms
      register: libvirt_names

    - name: Print output based on hostname
      ansible.builtin.debug:
        msg: "{{ item }} is in the list"
      loop: "{{ libvirt_names.list_vms }}"
