- name: Create a virtual machine
  hosts: localhost
  vars_files: ../vault.yml
  tasks:
    - name: Create VM
      redhat.openshift.k8s:
        state: present
        template: ../templates/bklab-rhel9-template.yml